apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nest-sqlite.fullname" . }}
  labels:
    {{- include "nest-sqlite.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.ENVIRONMENT | quote}}
  DATABASE_CONNECTION_STRING: {{ .Values.DATABASE_CONNECTION_STRING | quote}}
  JWT_SECRET_KEY: {{ .Values.JWT_SECRET_KEY | quote}}
  JWT_EXPIRES_IN: {{ .Values.JWT_EXPIRES_IN | quote }}
  TRACE_EXPORTER_URL: {{ .Values.TRACE_EXPORTER_URL | quote }}
