apiVersion: v1
kind: Secret
metadata:
  name: github-docker-registry
  labels:
    {{- include "nest-sqlite.labels" . | nindent 4 }}
data:
  .dockerconfigjson: CHANGE_ME
type: kubernetes.io/dockerconfigjson
