apiVersion: v1
kind: Service
metadata:
  name: {{ include "nest-sqlite.fullname" . }}
  labels:
    {{- include "nest-sqlite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.name }}
      name: {{ .Values.service.ports.http.name }}
      protocol: TCP
    - port: {{ .Values.service.ports.httpMetrics.port }}
      targetPort: {{ .Values.service.ports.httpMetrics.name }}
      name: {{ .Values.service.ports.httpMetrics.name }}
      protocol: TCP
  selector:
    {{- include "nest-sqlite.selectorLabels" . | nindent 4 }}
