apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nest-sqlite.fullname" . }}
  labels:
    {{- include "nest-sqlite.labels" . | nindent 4 }}
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "nest-sqlite.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.ports.httpMetrics.name }}
      interval: 10s
      path: /metrics
