name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u SetupCZ -p ${{secrets.DOCKER_REPOSITORY_KEY}} ghcr.io
        docker build . --tag ghcr.io/setupcz/nestjs-sqlite-ghcr:latest --platform linux/arm64
        docker push ghcr.io/setupcz/nestjs-sqlite-ghcr:latest
